[toolchain]

[features]
resolution = true
skip-lint = true

[programs.localnet]
intraverse_memefight = "7k4a1fPARX2LLzKwD8FY8rGLvapfbikFkWL2cF1KurAX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"